### ISSUE TITLE
Driver Compile Error on Debian 10 Buster 4.19.0-17-amd64

### ISSUE THREAD

**Issue by ivo443** [rchovan/npreal2#11]
Hi all

Kernel 4.x.x Branch will not compile on:

Debian Buster 10
4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux 
All Dependencies installed.
Kernel Source present

>> Compiles fine on  4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux <<

any help will be nice ..

Thank you
Ivo

I'll get the following:

/usr/src/moxa/mxinst

Building driver...

If you want to use secure communication with target,
you might choose [y] to enable the SSL function.
Note: This function support RealCOM with secure mode only.
Do you want to enable secure function? [y/N].
n
make -C /lib/modules/4.19.0-17-amd64/build M=/usr/src/moxa modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-17-amd64'
  CC [M]  /usr/src/moxa/npreal2.o
/usr/src/moxa/npreal2.c: In function ‘npreal_close’:
/usr/src/moxa/npreal2.c:987:20: error: ‘ASYNC_CLOSING’ undeclared (first use in this function); did you mean ‘ASYNC_SAK’?
  if (info->flags & ASYNC_CLOSING) {
                    ^~~~~~~~~~~~~
                    ASYNC_SAK
/usr/src/moxa/npreal2.c:987:20: note: each undeclared identifier is reported only once for each function it appears in
/usr/src/moxa/npreal2.c:1003:21: error: ‘ASYNC_NORMAL_ACTIVE’ undeclared (first use in this function); did you mean ‘ASYNC_CALLOUT_ACTIVE’?
  if ( info->flags & ASYNC_NORMAL_ACTIVE )
                     ^~~~~~~~~~~~~~~~~~~
                     ASYNC_CALLOUT_ACTIVE
/usr/src/moxa/npreal2.c: In function ‘npreal_hangup’:
/usr/src/moxa/npreal2.c:1605:20: error: ‘ASYNC_CLOSING’ undeclared (first use in this function); did you mean ‘ASYNC_SAK’?
  if (info->flags & ASYNC_CLOSING)
                    ^~~~~~~~~~~~~
                    ASYNC_SAK
/usr/src/moxa/npreal2.c: In function ‘npreal_check_modem_status’:
/usr/src/moxa/npreal2.c:1633:22: error: ‘ASYNC_CHECK_CD’ undeclared (first use in this function); did you mean ‘TTY_PORT_CHECK_CD’?
  if ( (info->flags & ASYNC_CHECK_CD) && (is_dcd_changed))
                      ^~~~~~~~~~~~~~
                      TTY_PORT_CHECK_CD
/usr/src/moxa/npreal2.c: In function ‘npreal_block_til_ready’:
/usr/src/moxa/npreal2.c:1698:22: error: ‘ASYNC_NORMAL_ACTIVE’ undeclared (first use in this function); did you mean ‘ASYNC_CALLOUT_ACTIVE’?
   if ( info->flags & ASYNC_NORMAL_ACTIVE )
                      ^~~~~~~~~~~~~~~~~~~
                      ASYNC_CALLOUT_ACTIVE
/usr/src/moxa/npreal2.c:1754:46: error: ‘ASYNC_CLOSING’ undeclared (first use in this function); did you mean ‘ASYNC_SAK’?
   if ( tty_hung_up_p(filp) || (info->flags & ASYNC_CLOSING) )
                                              ^~~~~~~~~~~~~
                                              ASYNC_SAK
/usr/src/moxa/npreal2.c: In function ‘npreal_startup’:
/usr/src/moxa/npreal2.c:1853:21: error: ‘ASYNC_INITIALIZED’ undeclared (first use in this function); did you mean ‘VM_UNINITIALIZED’?
  if ( info->flags & ASYNC_INITIALIZED )
                     ^~~~~~~~~~~~~~~~~
                     VM_UNINITIALIZED
/usr/src/moxa/npreal2.c: In function ‘npreal_shutdown’:
/usr/src/moxa/npreal2.c:2084:23: error: ‘ASYNC_INITIALIZED’ undeclared (first use in this function); did you mean ‘VM_UNINITIALIZED’?
  if ( !(info->flags & ASYNC_INITIALIZED) )
                       ^~~~~~~~~~~~~~~~~
                       VM_UNINITIALIZED
/usr/src/moxa/npreal2.c:2117:19: error: ‘ASYNC_NORMAL_ACTIVE’ undeclared (first use in this function); did you mean ‘ASYNC_CALLOUT_ACTIVE’?
  info->flags &= ~(ASYNC_NORMAL_ACTIVE|ASYNC_CALLOUT_ACTIVE|ASYNC_INITIALIZED|ASYNC_CLOSING);
                   ^~~~~~~~~~~~~~~~~~~
                   ASYNC_CALLOUT_ACTIVE
/usr/src/moxa/npreal2.c:2117:78: error: ‘ASYNC_CLOSING’ undeclared (first use in this function); did you mean ‘ASYNC_SAK’?
  info->flags &= ~(ASYNC_NORMAL_ACTIVE|ASYNC_CALLOUT_ACTIVE|ASYNC_INITIALIZED|ASYNC_CLOSING);
                                                                              ^~~~~~~~~~~~~
                                                                              ASYNC_SAK
/usr/src/moxa/npreal2.c: In function ‘npreal_port_init’:
/usr/src/moxa/npreal2.c:2526:19: error: ‘ASYNC_CHECK_CD’ undeclared (first use in this function); did you mean ‘TTY_PORT_CHECK_CD’?
   info->flags &= ~ASYNC_CHECK_CD;
                   ^~~~~~~~~~~~~~
                   TTY_PORT_CHECK_CD
/usr/src/moxa/npreal2.c: In function ‘npreal_set_serial_info’:
/usr/src/moxa/npreal2.c:2897:21: error: ‘ASYNC_INITIALIZED’ undeclared (first use in this function); did you mean ‘VM_UNINITIALIZED’?
  if ( info->flags & ASYNC_INITIALIZED )
                     ^~~~~~~~~~~~~~~~~
                     VM_UNINITIALIZED
/usr/src/moxa/npreal2.c: In function ‘npreal_net_write’:
/usr/src/moxa/npreal2.c:3889:20: error: ‘ASYNC_CLOSING’ undeclared (first use in this function); did you mean ‘ASYNC_SAK’?
  if (info->flags & ASYNC_CLOSING)
                    ^~~~~~~~~~~~~
                    ASYNC_SAK
/usr/src/moxa/npreal2.c: In function ‘npreal_do_session_recovery’:
/usr/src/moxa/npreal2.c:4240:20: error: ‘ASYNC_INITIALIZED’ undeclared (first use in this function); did you mean ‘VM_UNINITIALIZED’?
  if (info->flags & ASYNC_INITIALIZED)
                    ^~~~~~~~~~~~~~~~~
                    VM_UNINITIALIZED
make[4]: *** [/usr/src/linux-headers-4.19.0-17-common/scripts/Makefile.build:315: /usr/src/moxa/npreal2.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-17-common/Makefile:1562: _module_/usr/src/moxa] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-17-amd64'
make: *** [Makefile:72: module] Error 2
Check Driver...
FAILED !!!

Install Not Completed !

**Comment by Rha25** [comment]
I'm also getting the same error, no way to make it work.
Eventually I've been able to build some version found on the internet, [here](https://moxa.ru/forum/index.php?/topic/69218-ошибка-компиляции-moxa-nport-server-real-tty-driver/)

The driver builds, installs, runs... but no communication really working then

**Comment by rchovan** [comment]
NOT MAINTAINED ANYMORE

due to lack of time and lot of issues I've stopped using MOXA TTY server. I've switched to USB-1Wire convertor.
If you have issues, look at the AUR repository, it is still maintained, and you can apply patches manually.
